apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: signalfx-cadvisord
  name: signalfx-cadvisord
  namespace: default
spec:
  replicas: 1
  selector:
    name: signalfx-cadvisord
  template:
    metadata:
      labels:
        app: signalfx-cadvisord
        name: signalfx-cadvisord
    spec:
      containers:
      - env:
        - name: SFX_ENDPOINT
          value: "https://ingest.signalfx.com"
        - name: SFX_API_TOKEN
          value: ""
        - name: CLUSTER_NAME
          value: "us-west-2a"
        - name: SEND_INTERVAL
          value: "2m"
        - name: CADVISOR_PORT
          value: "4194"
        - name: NODE_SERVICE_DISCOVERY_INTERVAL
          value: "5m"
        - name: KUBE_USER
          value: ""
        - name: KUBE_PASS
          value: ""
        image: michaeltrobinson/signalfx-cadvisord:latest
        imagePullPolicy: Always
        name: scraper
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs
